[[policy]]
package_name = "bin.mt.plus"
cpu_config = "high"
gpu_config = "ultra"
gpa_config = "enabled"
game_zone = "zone1"
thermal_frame = "balanced"
fps_stabilizer = "on"
refresh_rate = "90"
resv_8 = "default"
resv_13 = "default"
unity_game_boost = "enabled"

[[policy]]
# 定义第一个应用的配置
package_name = "com.miHoYo.Yuanshen"
cpu_config = "high"
gpu_config = "ultra"
gpa_config = "enabled"
game_zone = "zone1"
thermal_frame = "jjndwiwodkncncsiowsndcxii"
fps_stabilizer = "on"
refresh_rate = "90"
resv_8 = "default"
resv_13 = "default"
unity_game_boost = "enabled"
