//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "BPRectInfoBean")]
pub struct Model {
    #[sea_orm(column_name = "mId", primary_key)]
    pub m_id: i32,
    pub short_side: i32,
    pub width: i32,
    pub left_start: i32,
    pub right_start: i32,
    pub top: i32,
    pub v_gap: i32,
    pub rect_size: i32,
    pub enter_left: i32,
    pub enter_right: i32,
    pub enter_first: i32,
    pub enter_second: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
