//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "LightningStartBean")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub start_time: i32,
    #[sea_orm(column_type = "Text")]
    pub package_name: String,
    pub end_time: i32,
    pub time_usage: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
