//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "LocalLogBean")]
pub struct Model {
    #[sea_orm(column_name = "mId", primary_key)]
    pub m_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub msg: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
