//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "LOLShockInfoBean")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub short_side: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub width: i32,
    pub left_lol: i32,
    pub right_lol: i32,
    pub top_lol: i32,
    pub bottom_lol: i32,
    pub gap_lol: i32,
    pub diff_lol: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
