//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod android_metadata;
pub mod bp_rect_info_bean;
pub mod db_sp_bean;
pub mod default_game_info_bean;
pub mod game_shock_info_bean;
pub mod hero_info_bean;
pub mod lightning_start_bean;
pub mod local_log_bean;
pub mod lol_shock_info_bean;
pub mod package_config_bean;
pub mod package_info_bean;
pub mod pre_down_info_bean;
pub mod room_master_table;
pub mod thermal_config_bean;
pub mod type_info_bean;
pub mod ui_flag_info_bean;
