//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "PackageConfigBean")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub package_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub type_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub feature_flag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cpu_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gpu_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub io_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub dynamic_resolution: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub launch_boost: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub usage_power_ratio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub memory_clear: Option<String>,
    #[sea_orm(column_name = "frameBoost", column_type = "Text", nullable)]
    pub frame_boost: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refresh_rate: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gpa_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sdk_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub modified_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub other: Option<String>,
    pub from_server: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub data_collector: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub simple_client: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cool_ex: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lighting_start: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prison: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cosa_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tgpa_client: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_zone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bind_core: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub decision: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub control: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_loading: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_loading_finish: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_start: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_stop: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_switch: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub perf_mode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub target_fps: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thermal_frame: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_2: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_3: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_4: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_5: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_6: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_7: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_8: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_9: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_10: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_11: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_12: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resv_13: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub unity_game_boost: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub fps_stabilizer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bg_update: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
