//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "PackageInfoBean")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub package_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub apk_name: Option<String>,
    pub type_id: i32,
    pub user_type_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub developer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub app_store: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_update_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub create_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub update_time: Option<String>,
    pub from_server: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
